#!/bin/bash

emacsclient -a false -e 't' 1>/dev/null 2>/dev/null
SERVER_CLOSED=$?

if [ $SERVER_CLOSED -eq 0 ]; then
	echo "Shutting down emacs server..."
	emacsclient -e "(kill-emacs)"
else
	echo "Starting emacs server..."
	/bin/emacs --daemon 1>/dev/null 2>/dev/null
fi
