#!/bin/bash

GIT_SSH="git@github.com:Bard-Gaming/Epitech-Libraries.git"
OUTPUT_DIR="lib"
PROJECT_CONF_FILE=".project_keep"

# -------------- Replace existing dir -------------- :
if [ -d "$OUTPUT_DIR" ]; then
	read -p "Replace existing \"$OUTPUT_DIR\"? (y/n) " REPLACE_DIR
	
	if [ "$REPLACE_DIR" = "y" ]; then
		rm -rf "$OUTPUT_DIR"
	else
		exit
	fi
fi
rm -rf "$OUTPUT_DIR"

# ----------------- Clone lib repo ----------------- : 
git clone "$GIT_SSH" "$OUTPUT_DIR" 2>/dev/null
if [ "$?" -ne "0" ]; then
	echo "import-lib: Error cloning library repo"
	exit
fi

# --------------- Pick & choose libs --------------- :
read -r -p "Libraries to keep: " LIBS_TO_KEEP

if [ -z "$LIBS_TO_KEEP" ]; then
	echo ""
	exit
fi

cd "$OUTPUT_DIR"  # cd can't fail here
make -s $LIBS_TO_KEEP no_repo  # keep LIBS_TO_KEEP unquoted since we want word splitting here
project-utils remove-unwanted
rm -f "$PROJECT_CONF_FILE"
cd - 1>/dev/null
