#!/bin/bash

# Get project name:
read -p "Project name: " PROJECT_NAME

# Constants:
TEMPLATE_DIR="$HOME/.custom_scripts/templates"
INCLUDE_DIR="$(pwd)/$PROJECT_NAME/include"

# Check if project name is a valid name
# (only alphanumerics and '_' are allowed):
if [[ "$PROJECT_NAME" =~ [^a-zA-Z0-9\_] ]]; then
    echo "new-project: $PROJECT_NAME: invalid project name"
    exit
fi

# Create project dir if it doesn't exist already
if [ ! -d $PROJECT_NAME ]; then
    mkdir $PROJECT_NAME
fi
cd $PROJECT_NAME

# Check for already present files to prevent
# accidentally creating the same project twice:
if [ -f .gitignore ]; then
    echo "new-project: $PROJECT_NAME: project already exists"
    exit
fi

# Create project files/dirs:
touch .gitignore
touch main.c
touch Makefile
touch .dir-locals.el
mkdir include

cat "$TEMPLATE_DIR/gitignore" | sed "s/\[PROJECT_NAME\]/$PROJECT_NAME/" >> .gitignore
cat "$TEMPLATE_DIR/main" | sed "s/\[PROJECT_NAME\]/$PROJECT_NAME/" >> main.c
cat "$TEMPLATE_DIR/makefile" | sed "s/\[PROJECT_NAME\]/$PROJECT_NAME/" >> Makefile
cat "$TEMPLATE_DIR/dir_locals" | sed "s;\[INCLUDE_DIR\];$INCLUDE_DIR;" >> .dir-locals.el


# Project config:
intercept-build make -s
make -s fclean
