#!/bin/bash

SCHEDULE_FILE=".rmschedule"

trim_whitespace() {
    echo "$1" | xargs
}

# Utility functions
is_in_schedule() {
    FILE="$(trim_whitespace "$1")"

    while IFS= read -r LINE; do
        SCHED_FILE="$(trim_whitespace "$LINE")"
        if [ "$FILE" = "$SCHED_FILE" ]; then
            echo 'true'
        fi
    done < $SCHEDULE_FILE
    echo 'false'
}

# Check if schedule file exists
if ! [ -f $SCHEDULE_FILE ]; then
    echo "Error: No .rmschedule file found" 1>&2
    exit 1
fi

echo >> $SCHEDULE_FILE  # Add a newline in case it's missing


# Recursively delete everything that isn't in the schedule
for FILE in $(ls -1A); do
    if [ "$FILE" != "$SCHEDULE_FILE" ] && [ "$(is_in_schedule "$FILE")" = "false" ]; then
        rm -rf "./$FILE"
    fi
done

# When done, remove schedule file
rm -f $SCHEDULE_FILE
